name: Validate commit messages

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  validate:
    uses: nirarg/migration-planner-workflows/.github/workflows/validate-commit-messages.yml@main
    with:
      types: '["feat","fix","ci","build","chore","docs","refactor","test","style","perf"]'
      jira-pattern: "ECOPROJECT-[0-9]+"
